name: salesresgistrator
description: "Sales tracking app. Record sales, view history, generate reports. Simple, intuitive interface."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  crud_table: ^0.0.6

  # Usa la versión compatible de intl
  intl: 0.19.0  # Asegúrate de usar esta versión para evitar conflictos

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true